services:
  backend1:
    build:
      context: .
      dockerfile: Dockerfile
    image: backend
    container_name: backend1
    environment:
      PROJECT_NAME: 백엔드 서버1

  backend2:
    image: backend
    container_name: backend2
    environment:
      PROJECT_NAME: 백엔드 서버2

  backend3:
    image: backend
    container_name: backend3
    environment:
      PROJECT_NAME: 백엔드 서버3

  nginx:
    image: nginx:1.25
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend1
      - backend2
      - backend3
